title: University shtuff
email: r.boers1@students.uu.nl
lang: nl
description: >-
  Dit is een kopie van mijn originele school stuff website, maar dan voor de universiteit. Ik plaats hier mijn samenvattingen in de hoop dat iemand anders er nog iets aan heeft.
url: "https://uni.geheimesite.nl"
github_username: RobinBoers
exclude:
  - Bakefile
plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-sitemap
