mindmap
  root((Rowan Atkinson))
    Acteur
      Film
        Verhaal
          Conflictmodel / dramatische boog
            Evenwicht
            Conflict
            Ontwikkeling
          Script
          Acts
            Drie-actsstructuur
          Scenes
          Storyboard
            Personages
              Round
              Flat
        Decor
          Rekwisieten
          Kostuums
        Montage
            Soundtrack
            SFX
        Camera
          Cinematografie
            Perspectief
            Belichting
            Kleurgebruik
            Contrast
            Kader
            Compositie
              Regel van derden
    Comedian
      Humor
        Situationele humor
        Taalhumor
        Absurde humor
        Zwarte humor
        Parodie
        Satire
      
